//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParrotPortalSampleApp.WCF.ParrotProductInfo {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PortalResultOfArrayOfProductInformationAmSG9_SwV", Namespace="http://schemas.datacontract.org/2004/07/CommonDataDefinitions.Portal.Common")]
    [System.SerializableAttribute()]
    public partial class PortalResultOfArrayOfProductInformationAmSG9_SwV : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ParrotPortalSampleApp.WCF.ParrotProductInfo.ProductInformation> DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ParrotPortalSampleApp.WCF.ParrotProductInfo.ProductInformation> Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductInformation", Namespace="http://schemas.datacontract.org/2004/07/CommonDataDefinitions.Portal.ProductInfo")]
    [System.SerializableAttribute()]
    public partial class ProductInformation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ParrotPortalSampleApp.WCF.ParrotProductInfo.RelatedProduct> AlternativeProductsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CustomerPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CustomerPriceWithTaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CustomerTaxAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailedDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> FuturePriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ParrotPortalSampleApp.WCF.ParrotProductInfo.IntermediatePack> IntermediatePacksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ParrotPortalSampleApp.WCF.ParrotProductInfo.RelatedProduct> KitItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductBarCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> ProductDocumentLinksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> ProductImageLinksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ParrotPortalSampleApp.WCF.ParrotProductInfo.PromotionInformation PromotionInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal RetailPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StockCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StockIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ParrotPortalSampleApp.WCF.ParrotProductInfo.PortalWarehouseStockLevel> WarehouseStockLevelsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ParrotPortalSampleApp.WCF.ParrotProductInfo.RelatedProduct> AlternativeProducts {
            get {
                return this.AlternativeProductsField;
            }
            set {
                if ((object.ReferenceEquals(this.AlternativeProductsField, value) != true)) {
                    this.AlternativeProductsField = value;
                    this.RaisePropertyChanged("AlternativeProducts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CustomerPrice {
            get {
                return this.CustomerPriceField;
            }
            set {
                if ((this.CustomerPriceField.Equals(value) != true)) {
                    this.CustomerPriceField = value;
                    this.RaisePropertyChanged("CustomerPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CustomerPriceWithTax {
            get {
                return this.CustomerPriceWithTaxField;
            }
            set {
                if ((this.CustomerPriceWithTaxField.Equals(value) != true)) {
                    this.CustomerPriceWithTaxField = value;
                    this.RaisePropertyChanged("CustomerPriceWithTax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CustomerTaxAmount {
            get {
                return this.CustomerTaxAmountField;
            }
            set {
                if ((this.CustomerTaxAmountField.Equals(value) != true)) {
                    this.CustomerTaxAmountField = value;
                    this.RaisePropertyChanged("CustomerTaxAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DetailedDescription {
            get {
                return this.DetailedDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailedDescriptionField, value) != true)) {
                    this.DetailedDescriptionField = value;
                    this.RaisePropertyChanged("DetailedDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> FuturePrice {
            get {
                return this.FuturePriceField;
            }
            set {
                if ((this.FuturePriceField.Equals(value) != true)) {
                    this.FuturePriceField = value;
                    this.RaisePropertyChanged("FuturePrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ParrotPortalSampleApp.WCF.ParrotProductInfo.IntermediatePack> IntermediatePacks {
            get {
                return this.IntermediatePacksField;
            }
            set {
                if ((object.ReferenceEquals(this.IntermediatePacksField, value) != true)) {
                    this.IntermediatePacksField = value;
                    this.RaisePropertyChanged("IntermediatePacks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ParrotPortalSampleApp.WCF.ParrotProductInfo.RelatedProduct> KitItems {
            get {
                return this.KitItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.KitItemsField, value) != true)) {
                    this.KitItemsField = value;
                    this.RaisePropertyChanged("KitItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductBarCode {
            get {
                return this.ProductBarCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductBarCodeField, value) != true)) {
                    this.ProductBarCodeField = value;
                    this.RaisePropertyChanged("ProductBarCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> ProductDocumentLinks {
            get {
                return this.ProductDocumentLinksField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductDocumentLinksField, value) != true)) {
                    this.ProductDocumentLinksField = value;
                    this.RaisePropertyChanged("ProductDocumentLinks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> ProductImageLinks {
            get {
                return this.ProductImageLinksField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductImageLinksField, value) != true)) {
                    this.ProductImageLinksField = value;
                    this.RaisePropertyChanged("ProductImageLinks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ParrotPortalSampleApp.WCF.ParrotProductInfo.PromotionInformation PromotionInfo {
            get {
                return this.PromotionInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.PromotionInfoField, value) != true)) {
                    this.PromotionInfoField = value;
                    this.RaisePropertyChanged("PromotionInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal RetailPrice {
            get {
                return this.RetailPriceField;
            }
            set {
                if ((this.RetailPriceField.Equals(value) != true)) {
                    this.RetailPriceField = value;
                    this.RaisePropertyChanged("RetailPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StockCode {
            get {
                return this.StockCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.StockCodeField, value) != true)) {
                    this.StockCodeField = value;
                    this.RaisePropertyChanged("StockCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StockID {
            get {
                return this.StockIDField;
            }
            set {
                if ((this.StockIDField.Equals(value) != true)) {
                    this.StockIDField = value;
                    this.RaisePropertyChanged("StockID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ParrotPortalSampleApp.WCF.ParrotProductInfo.PortalWarehouseStockLevel> WarehouseStockLevels {
            get {
                return this.WarehouseStockLevelsField;
            }
            set {
                if ((object.ReferenceEquals(this.WarehouseStockLevelsField, value) != true)) {
                    this.WarehouseStockLevelsField = value;
                    this.RaisePropertyChanged("WarehouseStockLevels");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PromotionInformation", Namespace="http://schemas.datacontract.org/2004/07/CommonDataDefinitions.Portal.ProductInfo")]
    [System.SerializableAttribute()]
    public partial class PromotionInformation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ParrotPortalSampleApp.WCF.ParrotProductInfo.PromotionType PromoTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RequiredMinQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StockIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ParrotPortalSampleApp.WCF.ParrotProductInfo.PromotionType PromoType {
            get {
                return this.PromoTypeField;
            }
            set {
                if ((this.PromoTypeField.Equals(value) != true)) {
                    this.PromoTypeField = value;
                    this.RaisePropertyChanged("PromoType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RequiredMinQuantity {
            get {
                return this.RequiredMinQuantityField;
            }
            set {
                if ((this.RequiredMinQuantityField.Equals(value) != true)) {
                    this.RequiredMinQuantityField = value;
                    this.RaisePropertyChanged("RequiredMinQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StockID {
            get {
                return this.StockIDField;
            }
            set {
                if ((this.StockIDField.Equals(value) != true)) {
                    this.StockIDField = value;
                    this.RaisePropertyChanged("StockID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RelatedProduct", Namespace="http://schemas.datacontract.org/2004/07/CommonDataDefinitions.Portal.ProductInfo")]
    [System.SerializableAttribute()]
    public partial class RelatedProduct : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RelatedStockCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StockCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RelatedStockCode {
            get {
                return this.RelatedStockCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.RelatedStockCodeField, value) != true)) {
                    this.RelatedStockCodeField = value;
                    this.RaisePropertyChanged("RelatedStockCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StockCode {
            get {
                return this.StockCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.StockCodeField, value) != true)) {
                    this.StockCodeField = value;
                    this.RaisePropertyChanged("StockCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IntermediatePack", Namespace="http://schemas.datacontract.org/2004/07/CommonDataDefinitions.Portal.ProductInfo")]
    [System.SerializableAttribute()]
    public partial class IntermediatePack : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PackBarCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PackQTYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StockCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PackBarCode {
            get {
                return this.PackBarCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PackBarCodeField, value) != true)) {
                    this.PackBarCodeField = value;
                    this.RaisePropertyChanged("PackBarCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PackQTY {
            get {
                return this.PackQTYField;
            }
            set {
                if ((this.PackQTYField.Equals(value) != true)) {
                    this.PackQTYField = value;
                    this.RaisePropertyChanged("PackQTY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StockCode {
            get {
                return this.StockCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.StockCodeField, value) != true)) {
                    this.StockCodeField = value;
                    this.RaisePropertyChanged("StockCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PortalWarehouseStockLevel", Namespace="http://schemas.datacontract.org/2004/07/CommonDataDefinitions.Portal.ProductInfo")]
    [System.SerializableAttribute()]
    public partial class PortalWarehouseStockLevel : ParrotPortalSampleApp.WCF.ParrotProductInfo.PortalWarehouse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StockCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StockCode {
            get {
                return this.StockCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.StockCodeField, value) != true)) {
                    this.StockCodeField = value;
                    this.RaisePropertyChanged("StockCode");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PromotionType", Namespace="http://schemas.datacontract.org/2004/07/SharedTypes")]
    public enum PromotionType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        psAdditionalPercentage = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        psFixedPrice = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PortalWarehouse", Namespace="http://schemas.datacontract.org/2004/07/CommonDataDefinitions.Portal.ProductInfo")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ParrotPortalSampleApp.WCF.ParrotProductInfo.PortalWarehouseStockLevel))]
    public partial class PortalWarehouse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WarehouseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WarehouseDescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WarehouseCode {
            get {
                return this.WarehouseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.WarehouseCodeField, value) != true)) {
                    this.WarehouseCodeField = value;
                    this.RaisePropertyChanged("WarehouseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WarehouseDescription {
            get {
                return this.WarehouseDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.WarehouseDescriptionField, value) != true)) {
                    this.WarehouseDescriptionField = value;
                    this.RaisePropertyChanged("WarehouseDescription");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PortalResultOfArrayOfPortalWarehouseAmSG9_SwV", Namespace="http://schemas.datacontract.org/2004/07/CommonDataDefinitions.Portal.Common")]
    [System.SerializableAttribute()]
    public partial class PortalResultOfArrayOfPortalWarehouseAmSG9_SwV : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ParrotPortalSampleApp.WCF.ParrotProductInfo.PortalWarehouse> DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ParrotPortalSampleApp.WCF.ParrotProductInfo.PortalWarehouse> Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCF.ParrotProductInfo.IProductInfo")]
    public interface IProductInfo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInfo/GetProductInfoForCustomerForMultipleProducts", ReplyAction="http://tempuri.org/IProductInfo/GetProductInfoForCustomerForMultipleProductsRespo" +
            "nse")]
        ParrotPortalSampleApp.WCF.ParrotProductInfo.PortalResultOfArrayOfProductInformationAmSG9_SwV GetProductInfoForCustomerForMultipleProducts(System.Collections.Generic.List<string> StockCodes, string CustomerCode, System.Nullable<System.DateTime> PricingDate, System.Nullable<int> ChannelID, int PromoMinQuantity, string Password, bool GetSuspendedProducts);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInfo/GetProductInfoForCustomerForMultipleProducts", ReplyAction="http://tempuri.org/IProductInfo/GetProductInfoForCustomerForMultipleProductsRespo" +
            "nse")]
        System.Threading.Tasks.Task<ParrotPortalSampleApp.WCF.ParrotProductInfo.PortalResultOfArrayOfProductInformationAmSG9_SwV> GetProductInfoForCustomerForMultipleProductsAsync(System.Collections.Generic.List<string> StockCodes, string CustomerCode, System.Nullable<System.DateTime> PricingDate, System.Nullable<int> ChannelID, int PromoMinQuantity, string Password, bool GetSuspendedProducts);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInfo/GetProductInfoForCustomerForMultipleProductsUsing" +
            "Defaults", ReplyAction="http://tempuri.org/IProductInfo/GetProductInfoForCustomerForMultipleProductsUsing" +
            "DefaultsResponse")]
        ParrotPortalSampleApp.WCF.ParrotProductInfo.PortalResultOfArrayOfProductInformationAmSG9_SwV GetProductInfoForCustomerForMultipleProductsUsingDefaults(System.Collections.Generic.List<string> StockCodes, string CustomerCode, string Password, bool GetSuspendedProducts);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInfo/GetProductInfoForCustomerForMultipleProductsUsing" +
            "Defaults", ReplyAction="http://tempuri.org/IProductInfo/GetProductInfoForCustomerForMultipleProductsUsing" +
            "DefaultsResponse")]
        System.Threading.Tasks.Task<ParrotPortalSampleApp.WCF.ParrotProductInfo.PortalResultOfArrayOfProductInformationAmSG9_SwV> GetProductInfoForCustomerForMultipleProductsUsingDefaultsAsync(System.Collections.Generic.List<string> StockCodes, string CustomerCode, string Password, bool GetSuspendedProducts);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInfo/GetProductInfoForCustomerForMultipleProductsUsing" +
            "DefaultsWithWarehouseStock", ReplyAction="http://tempuri.org/IProductInfo/GetProductInfoForCustomerForMultipleProductsUsing" +
            "DefaultsWithWarehouseStockResponse")]
        ParrotPortalSampleApp.WCF.ParrotProductInfo.PortalResultOfArrayOfProductInformationAmSG9_SwV GetProductInfoForCustomerForMultipleProductsUsingDefaultsWithWarehouseStock(System.Collections.Generic.List<string> StockCodes, string CustomerCode, string Password, bool GetSuspendedProducts, System.Collections.Generic.List<string> WarehouseCodes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInfo/GetProductInfoForCustomerForMultipleProductsUsing" +
            "DefaultsWithWarehouseStock", ReplyAction="http://tempuri.org/IProductInfo/GetProductInfoForCustomerForMultipleProductsUsing" +
            "DefaultsWithWarehouseStockResponse")]
        System.Threading.Tasks.Task<ParrotPortalSampleApp.WCF.ParrotProductInfo.PortalResultOfArrayOfProductInformationAmSG9_SwV> GetProductInfoForCustomerForMultipleProductsUsingDefaultsWithWarehouseStockAsync(System.Collections.Generic.List<string> StockCodes, string CustomerCode, string Password, bool GetSuspendedProducts, System.Collections.Generic.List<string> WarehouseCodes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInfo/GetWarehouseInfo", ReplyAction="http://tempuri.org/IProductInfo/GetWarehouseInfoResponse")]
        ParrotPortalSampleApp.WCF.ParrotProductInfo.PortalResultOfArrayOfPortalWarehouseAmSG9_SwV GetWarehouseInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInfo/GetWarehouseInfo", ReplyAction="http://tempuri.org/IProductInfo/GetWarehouseInfoResponse")]
        System.Threading.Tasks.Task<ParrotPortalSampleApp.WCF.ParrotProductInfo.PortalResultOfArrayOfPortalWarehouseAmSG9_SwV> GetWarehouseInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInfo/IsConnectionUp", ReplyAction="http://tempuri.org/IProductInfo/IsConnectionUpResponse")]
        bool IsConnectionUp();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInfo/IsConnectionUp", ReplyAction="http://tempuri.org/IProductInfo/IsConnectionUpResponse")]
        System.Threading.Tasks.Task<bool> IsConnectionUpAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductInfoChannel : ParrotPortalSampleApp.WCF.ParrotProductInfo.IProductInfo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductInfoClient : System.ServiceModel.ClientBase<ParrotPortalSampleApp.WCF.ParrotProductInfo.IProductInfo>, ParrotPortalSampleApp.WCF.ParrotProductInfo.IProductInfo {
        
        public ProductInfoClient() {
        }
        
        public ProductInfoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductInfoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductInfoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductInfoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ParrotPortalSampleApp.WCF.ParrotProductInfo.PortalResultOfArrayOfProductInformationAmSG9_SwV GetProductInfoForCustomerForMultipleProducts(System.Collections.Generic.List<string> StockCodes, string CustomerCode, System.Nullable<System.DateTime> PricingDate, System.Nullable<int> ChannelID, int PromoMinQuantity, string Password, bool GetSuspendedProducts) {
            return base.Channel.GetProductInfoForCustomerForMultipleProducts(StockCodes, CustomerCode, PricingDate, ChannelID, PromoMinQuantity, Password, GetSuspendedProducts);
        }
        
        public System.Threading.Tasks.Task<ParrotPortalSampleApp.WCF.ParrotProductInfo.PortalResultOfArrayOfProductInformationAmSG9_SwV> GetProductInfoForCustomerForMultipleProductsAsync(System.Collections.Generic.List<string> StockCodes, string CustomerCode, System.Nullable<System.DateTime> PricingDate, System.Nullable<int> ChannelID, int PromoMinQuantity, string Password, bool GetSuspendedProducts) {
            return base.Channel.GetProductInfoForCustomerForMultipleProductsAsync(StockCodes, CustomerCode, PricingDate, ChannelID, PromoMinQuantity, Password, GetSuspendedProducts);
        }
        
        public ParrotPortalSampleApp.WCF.ParrotProductInfo.PortalResultOfArrayOfProductInformationAmSG9_SwV GetProductInfoForCustomerForMultipleProductsUsingDefaults(System.Collections.Generic.List<string> StockCodes, string CustomerCode, string Password, bool GetSuspendedProducts) {
            return base.Channel.GetProductInfoForCustomerForMultipleProductsUsingDefaults(StockCodes, CustomerCode, Password, GetSuspendedProducts);
        }
        
        public System.Threading.Tasks.Task<ParrotPortalSampleApp.WCF.ParrotProductInfo.PortalResultOfArrayOfProductInformationAmSG9_SwV> GetProductInfoForCustomerForMultipleProductsUsingDefaultsAsync(System.Collections.Generic.List<string> StockCodes, string CustomerCode, string Password, bool GetSuspendedProducts) {
            return base.Channel.GetProductInfoForCustomerForMultipleProductsUsingDefaultsAsync(StockCodes, CustomerCode, Password, GetSuspendedProducts);
        }
        
        public ParrotPortalSampleApp.WCF.ParrotProductInfo.PortalResultOfArrayOfProductInformationAmSG9_SwV GetProductInfoForCustomerForMultipleProductsUsingDefaultsWithWarehouseStock(System.Collections.Generic.List<string> StockCodes, string CustomerCode, string Password, bool GetSuspendedProducts, System.Collections.Generic.List<string> WarehouseCodes) {
            return base.Channel.GetProductInfoForCustomerForMultipleProductsUsingDefaultsWithWarehouseStock(StockCodes, CustomerCode, Password, GetSuspendedProducts, WarehouseCodes);
        }
        
        public System.Threading.Tasks.Task<ParrotPortalSampleApp.WCF.ParrotProductInfo.PortalResultOfArrayOfProductInformationAmSG9_SwV> GetProductInfoForCustomerForMultipleProductsUsingDefaultsWithWarehouseStockAsync(System.Collections.Generic.List<string> StockCodes, string CustomerCode, string Password, bool GetSuspendedProducts, System.Collections.Generic.List<string> WarehouseCodes) {
            return base.Channel.GetProductInfoForCustomerForMultipleProductsUsingDefaultsWithWarehouseStockAsync(StockCodes, CustomerCode, Password, GetSuspendedProducts, WarehouseCodes);
        }
        
        public ParrotPortalSampleApp.WCF.ParrotProductInfo.PortalResultOfArrayOfPortalWarehouseAmSG9_SwV GetWarehouseInfo() {
            return base.Channel.GetWarehouseInfo();
        }
        
        public System.Threading.Tasks.Task<ParrotPortalSampleApp.WCF.ParrotProductInfo.PortalResultOfArrayOfPortalWarehouseAmSG9_SwV> GetWarehouseInfoAsync() {
            return base.Channel.GetWarehouseInfoAsync();
        }
        
        public bool IsConnectionUp() {
            return base.Channel.IsConnectionUp();
        }
        
        public System.Threading.Tasks.Task<bool> IsConnectionUpAsync() {
            return base.Channel.IsConnectionUpAsync();
        }
    }
}
